### ISSUE TITLE
Doc updates for deploying the site

### ISSUE THREAD

**Issue by Jkrzy** [CBHSQ/findtreatment#486]
In addition to detailing our automated build and deploy pipline w/ Federalist, our documentation must detail the process for manually building and deploying the site. 

Let's work from this PR/branch #485.

**Comment by davemcorwin** [comment]
@Jkrzy pushed the following to #485 

# Deploying

## Automatic (recommended)

We use [Federalist](https://federalist.18f.gov/) for production and "preview" deployments.

Federalist is integrated with Github such that on each push to the `master` branch, the site is automatically and built and deployed to production, where it is immediately available at `findtreatment.gov`. In addition, this process also happens for all other branches in Github, which will be available at URLs specified by Federalist.

In order to build the site, Federalist will call the `federalist` npm script (`npm run federalist`) and deploy everything that is in the `_site` folder. More information can be found in the [Federalist Docs](https://federalist.18f.gov/documentation/node-on-federalist/).

## Manual

### Building the site
To build the site manually, just run `npm run federalist` from your command line or terminal. This requires that `node` and `npm` are installed on the machine and the steps in [Developing](./developing.md) have already been completed. The results of the build process will live in the `build` folder in the root of the project.

### Deploying the built site
This is a "static" application that consists only of the files in the `build` folder after following the previous step. To deploy, just place the contents of the `build` folder wherever your server of choice expects static files.

**Comment by Jkrzy** [comment]
Looking great @davemcorwin! 

For manual deploys, is anything needed to populate/replicate the environment vars or other configuration provided by Federalist? Like `PUBLIC_URL` and `REACT_APP_BRANCH`?

**Comment by davemcorwin** [comment]
Thanks @Jkrzy. I added some content around the environment variables, but there is nothing configured in Federalist, it is all in the repository itself in `.env` files.

**Comment by Jkrzy** [comment]
Right now, we're using `BRANCH` and `SITE_PREFIX` from Federalist, https://federalist.18f.gov/documentation/env-vars-on-federalist-builds/, to set some paths and [determine which API to hit ](https://github.com/18F/samhsa-prototype/blob/master/src/utils/api.js#L11). 

Think it would be better to refactor or just document and maybe add a new npm script that passes those in?

**Comment by davemcorwin** [comment]
Great point. Added some documentation around the variables provided by Federalist. Right now, we're not totally consistent about where we are using the env variables and where things are hardcoded, so a refactor would be nice, but not necessary right now. We should create an issue to address it.

**Comment by allisonnorman** [comment]
@Jkrzy - Can I close this and #487?

**Comment by Jkrzy** [comment]
Not this one, we still need some tweaks for a manual deploy.
